# This is a basic workflow to help you get started with Actions

name: Ubuntu
on: [push]
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: trombonist
      uses: csexton/debugger-action@master
